### ISSUE TITLE
No SIP RTP 

### ISSUE THREAD

**Issue by treblac** [jitsi/jitsi#160]
I am unable to get RTP during SIP calls after upgrading to 2.9.5477.  I see the error below and never get audio. I also downgraded to 2.9.5476 and see the same issue.  Downgrading to 2.9.5475 does not produce the error.

2015-10-09 16:42:25.041 SEVERE: [2247] impl.protocol.sip.SipStackSharing.logApplicationException().1116 An error occurred while processing event of type: javax.sip.DialogTerminatedEventjava.lang.NoClassDefFoundError: net/sf/fmj/media/rtp/RTCPTransmitterFactory  at org.jitsi.impl.neomedia.MediaServiceImpl.createMediaStream(MediaServiceImpl.java:410)
